services:
  dev-environment-python:
    build: .
    privileged: true
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - ../:/workdir/
    environment:
      - DEV_CONTAINER=1
    networks:
      - ebl-net
    ports:
      - "42042:42042"
      - "42043:42043"
      - "42069:42069"
      - "50000:5000"


networks:
  ebl-net:
    name: ebl
    external: true
